'use client';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';

import store from '@/redux/configureStore';
import { Provider } from 'react-redux';
import ClientApp from '@/components/ClientApp';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };
// const dir = localStorage.getItem('direction');

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Provider store={store}>
          <ClientApp>{children}</ClientApp>
        </Provider>
      </body>
    </html>
  );
}
